# Generated by Django 4.1.6 on 2023-05-19 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gas', '0004_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='month',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
