# Generated by Django 4.1.6 on 2023-05-20 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gas', '0005_booking_month'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True)),
                ('email', models.CharField(max_length=20, null=True)),
                ('contact', models.CharField(max_length=30, null=True)),
                ('price', models.CharField(max_length=30, null=True)),
                ('mode', models.CharField(max_length=30, null=True)),
                ('status', models.CharField(max_length=70, null=True)),
                ('paymentdate', models.CharField(max_length=30, null=True)),
                ('gastype', models.CharField(max_length=30, null=True)),
                ('day', models.CharField(max_length=30, null=True)),
            ],
        ),
    ]
