# Generated by Django 4.1.6 on 2023-05-20 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gas', '0006_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='invoiceid',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
