# Generated by Django 4.1.6 on 2023-05-22 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gas', '0007_payment_invoiceid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='dob',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
